# Generated by Django 5.0.3 on 2024-03-11 06:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(help_text='Id of a file', primary_key=True, serialize=False, verbose_name='파일 ID')),
                ('type', models.CharField(choices=[('F', 'Individual file'), ('P', 'Installation package')], help_text="Select file type among 'file' or 'package'", max_length=1, verbose_name="파일 타입 (파일'F' 또는 패키지'P' 중 택1)")),
                ('version', models.CharField(help_text='Enter version of file', max_length=32, verbose_name='파일 버전')),
                ('hash', models.CharField(help_text='Enter file sha512 hash in upper case hex string', max_length=256, unique=True, verbose_name='파일 해쉬')),
                ('name', models.CharField(help_text='Enter file name', max_length=64, verbose_name='파일 이름')),
                ('stored_path', models.CharField(blank=True, help_text='Enter stored path of file', max_length=1024, null=True, verbose_name='서버 저장 위치')),
                ('update_id', models.PositiveIntegerField(blank=True, help_text='Id of the update file', null=True, verbose_name='업데이트 파일 ID')),
                ('enable', models.BooleanField(blank=True, default=True, help_text='Enable using this file', verbose_name='업데이트 사용 여부')),
                ('register_date', models.DateTimeField(auto_now_add=True, help_text='First registered datetime', verbose_name='등록 일시')),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text='Last modified datetime', verbose_name='수정 일시')),
            ],
            options={
                'ordering': ['name', '-register_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(help_text='Id of a report', primary_key=True, serialize=False, verbose_name='리포트 ID')),
                ('userid', models.CharField(blank=True, help_text='UserId of who sends this report', max_length=256, null=True, verbose_name='사용자 아이디')),
                ('ip', models.CharField(blank=True, help_text="a list of IP addresses of who sends this report seperated by ';'", max_length=256, null=True, verbose_name='사용자 IP 주소목록(;로 구분)')),
                ('old_hash', models.CharField(help_text='sha512 hash in hexstring of the old file', max_length=256, verbose_name='이전 파일 SHA512 해쉬')),
                ('new_hash', models.CharField(help_text='sha512 hash in hexstring of the new file', max_length=256, verbose_name='신규 파일 SHA512 해쉬')),
                ('old_name', models.CharField(help_text='the name of the old file', max_length=64, verbose_name='이전 파일 이름')),
                ('new_name', models.CharField(help_text='the name of the new file', max_length=64, verbose_name='신규 파일 이름')),
                ('old_version', models.CharField(help_text='the version of the old file', max_length=32, verbose_name='이전 파일 버전')),
                ('new_version', models.CharField(help_text='the version of the new file', max_length=32, verbose_name='신규 파일 버전')),
                ('err_code', models.IntegerField(help_text='the error code that occured in updating process', verbose_name='에러 코드')),
                ('err_msg', models.CharField(blank=True, help_text='the description of error code', max_length=1024, null=True, verbose_name='에러 메시지')),
                ('report_date', models.DateTimeField(auto_now_add=True, help_text='reported datetime', verbose_name='보고 일시')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('hash'), name='hash_case_insensitive_unique', violation_error_message='hash already exists (case insensitive match)'),
        ),
    ]
