# Generated by Django 5.0.3 on 2024-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(blank=True, default='CURRENT_TIMESTAMP', help_text='Last modified datetime', verbose_name='수정 일시'),
        ),
        migrations.AlterField(
            model_name='file',
            name='register_date',
            field=models.DateTimeField(blank=True, default='CURRENT_TIMESTAMP', help_text='First registered datetime', verbose_name='등록 일시'),
        ),
    ]
