# Generated by Django 5.0.3 on 2024-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_file_last_modified_alter_file_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Last modified datetime', verbose_name='수정 일시'),
        ),
        migrations.AlterField(
            model_name='file',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, help_text='First registered datetime', verbose_name='등록 일시'),
        ),
        migrations.AlterField(
            model_name='file',
            name='update_id',
            field=models.IntegerField(blank=True, help_text='Id of the update file', null=True, verbose_name='업데이트 파일 ID'),
        ),
    ]
