# Generated by Django 5.0.3 on 2024-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_file_last_modified_alter_file_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(help_text='File sha512 hash in upper case hex string', max_length=256, unique=True, verbose_name='파일 해쉬'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text='File name', max_length=64, verbose_name='파일 이름'),
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_path',
            field=models.CharField(blank=True, help_text='Stored path of file', max_length=1024, null=True, verbose_name='서버 저장 위치'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('F', '개별 파일'), ('P', '설치 패키지')], help_text="Select file type among 'file' or 'package'", max_length=1, verbose_name='파일 타입'),
        ),
        migrations.AlterField(
            model_name='file',
            name='update_id',
            field=models.IntegerField(blank=True, help_text='Id of the newer version of this file or package', null=True, verbose_name='업데이트 파일 ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(help_text='Version of file', max_length=32, verbose_name='파일 버전'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ip',
            field=models.CharField(blank=True, help_text="a list of IP addresses of who sends this report seperated by ';'", max_length=256, null=True, verbose_name='사용자 IP 주소목록'),
        ),
    ]
