# Generated by Django 5.0.3 on 2024-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_file_hash_alter_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('file_upload', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
            ],
        ),
    ]
