# Generated by Django 5.0.3 on 2024-03-11 09:52

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_path',
            field=models.FileField(blank=True, help_text='Stored path of file', max_length=1024, null=True, upload_to=catalog.models.user_directory_path, verbose_name='서버 저장 경로'),
        ),
    ]
