# Generated by Django 5.0.3 on 2024-03-11 11:13

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_delete_fileupload_alter_file_stored_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, editable=False, help_text='File sha512 hash in upper case hex string', max_length=256, unique=True, verbose_name='파일 해쉬'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(editable=False, help_text='File name', max_length=256, verbose_name='파일 이름'),
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_path',
            field=models.FileField(blank=True, help_text='Stored path of file', max_length=1024, null=True, upload_to=catalog.models.user_directory_path, verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(default='1.0', help_text='Version of file', max_length=32, verbose_name='파일 버전'),
        ),
    ]
