# Generated by Django 5.0.3 on 2024-03-12 01:27

import catalog.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_file_hash_alter_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='hash_case_insensitive_unique',
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, editable=False, help_text='File sha256 hash in lower case hex string', max_length=256, unique=True, verbose_name='파일 해쉬'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='파일 ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_path',
            field=models.FileField(blank=True, help_text='파일 경로', max_length=1024, null=True, upload_to=catalog.models.user_directory_path, validators=[catalog.models.FileValidator()], verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('F', '개별 파일'), ('P', '설치 패키지')], help_text='개별 파일, 설치 패키지 중 택1', max_length=1, verbose_name='파일 타입'),
        ),
        migrations.AlterField(
            model_name='file',
            name='update_id',
            field=models.IntegerField(blank=True, help_text='이 파일의 업데이트(신버전)에 해당하는 파일의 파일ID', null=True, verbose_name='업데이트 파일 ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(default='1.0', help_text='File Version이 명시된 윈도우 실행파일의 경우 자동으로 해당 버전 적용', max_length=32, verbose_name='파일 버전'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(models.F('stored_path'), name='stored_path_unique', violation_error_message='file already exists'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('hash'), name='hash_case_insensitive_unique', violation_error_message='hash already exists (case insensitive match)'),
        ),
    ]
