# Generated by Django 5.0.3 on 2024-04-04 05:27

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_file_hash_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, editable=False, help_text='File sha256 hash in lower case hex string', max_length=256, verbose_name='파일 해쉬'),
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_path',
            field=models.FileField(blank=True, help_text='파일 경로', max_length=1024, null=True, upload_to=catalog.models.user_directory_path, verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='file',
            name='update_id',
            field=models.IntegerField(blank=True, help_text='이 파일로 업데이트할(구버전) 파일의 파일ID', null=True, verbose_name='업데이트할 파일ID'),
        ),
    ]
