# Generated by Django 5.0.3 on 2024-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_file_hash_alter_file_stored_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ip',
            field=models.CharField(blank=True, help_text="a list of IP addresses of who sends this report seperated by ';'", max_length=1024, null=True, verbose_name='사용자 IP 주소목록'),
        ),
    ]
